<!doctype html>
<html>
<head>
	<title>Vk Bot Web UI</title>
	<link rel="stylesheet" href="../css/bootstrap.min.css">
	<link rel="stylesheet" href="../css/style.css">
</head>
<body>
<div class="container-fluid">
	<h1>Vk Bot Setup</h1>

	<p>Comparison operator - <b>equals</b>, or <b>contains</b></p>
	<p>Each message can have more than random answer, you can separate them with "|"</p>
	<p>User IDs and Chat IDs - you can fill one of them, if filtering is required (comma separated numbers)</p>

	<form method="post">
		<table class="table rules">
			<thead>
			<tr>
				<th>Comparison operator</th>
				<th>Message</th>
				<th>Answer</th>
				<th>User IDs</th>
				<th>Chat Ids</th>
				<th width="200"></th>
			</tr>
			</thead>
			<tbody>
			<?php foreach ($rules as $rule) { ?>
				<tr>
					<td><input placeholder="Operation" name="operation[]" type="text"
							   value="<?php echo $rule['operation']; ?>"/></td>
					<td><input placeholder="Message" name="message_in[]" type="text"
							   value="<?php echo $rule['message_in']; ?>"/></td>
					<td><input placeholder="Answer" name="message_out[]" type="text"
							   value="<?php echo $rule['message_out']; ?>"/></td>
					<td><input placeholder="User IDs" name="users[]" type="text"
							   value="<?php echo $rule['users']; ?>"/></td>
					<td><input placeholder="Chat IDs" name="chats[]" type="text" value="<?php echo $rule['chats']; ?>"/>
					</td>
					<td><a class="remove">Remove rule</a></td>
				</tr>
			<?php } ?>
			</tbody>
		</table>

		<input type="submit" name="create" value="Add more"/>
		<input type="submit" name="submit" value="Save changes"/>
	</form>
</div>
<script>
	window.onload = function () {
		var rules = document.querySelector('.rules');

		rules.addEventListener('click', function (e) {
			if (e.target.className === 'remove') {
				var rule = e.target.parentNode.parentNode;
				rule.parentNode.removeChild(rule);
			}
		});
	};
</script>
</body>
</html>

